### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327

### ISSUE THREAD

**Issue by MrMaaoui** [DrSleep/DenseTorch#7]
Good evening, 

I'm trying to use DenseTorch to train a multi task module on a custom created dataset (rgb, masks and depth with the masks and depth being grayscale). whenever I'm trying to run the training I get the following error that I couldn't solve:

`Traceback (most recent call last):
  File "train.py", line 82, in <module>
    dt.engine.train(model1, optims, [crit_segm, crit_depth], trainloader, loss_coeffs)
  File "/media/pfe_historiar/data/dataset/DenseTorch-master/densetorch/engine/trainval.py", line 80, in train
    target.squeeze(dim=1),
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/pfe_historiar/data/dataset/DenseTorch-master/densetorch/engine/losses.py", line 27, in forward
    c = 0.2 * torch.max(err)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327`

Any recommendations on how to solve this issue?

The full terminal log is in this file [log.txt](https://github.com/DrSleep/DenseTorch/files/4765225/log.txt).

**Comment by DrSleep** [comment]
What is the channel dimension of your segmentation classifier (aka `num_classes[0]` in [config](https://github.com/DrSleep/DenseTorch/blob/master/examples/multitask/config.py#L15)) ? And what is the largest label in your segmentation masks? When computing the segmentation cross-entropy loss, the largest label must be lower than the channel dimension of the classifier, otherwise you will see that error (more info [here in pytorch docs](https://pytorch.org/docs/stable/nn.html#torch.nn.CrossEntropyLoss)).

**Comment by MrMaaoui** [comment]
Thank you for your response,
converting segmented ground truth into class ids solved it
